### ISSUE TITLE
update gems

### ISSUE THREAD

**Issue by kirantpatil** [ModusCreateOrg/cucumber-watir#1]
Namaste,

While doing bundle install it installed watir-webdriver version as below.
Installing watir-webdriver 0.6.10

But the current version of watir-webdriver is 0.9.1.

Could you please update all the gems to latest stable version ?

Dhanyavaada,
Kiran.

**Comment by bkone** [comment]
please run `bundle update` to update all gems

**Comment by kirantpatil** [comment]
thanks.
