### ISSUE TITLE
App doesn't exist /home/kpatil/Documents/books/testcasedb/cucumber-watir/apps/Movies.app (RuntimeError)

### ISSUE THREAD

**Issue by kirantpatil** [ModusCreateOrg/cucumber-watir#2]
Namaste,

I am getting below error while executing on Fedora 22 Linux x86_64.

$ cucumber features/search.feature 

Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /home/kpatil/Documents/books/testcasedb/cucumber-watir/features/support/env.rb:4:in `<top (required)>'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in`load'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:142:in`load_file'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in`each'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:254:in`load_step_definitions'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:62:in `run!'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in`execute!'
  /home/kpatil/.gem/ruby/gems/cucumber-2.3.2/bin/cucumber:8:in `<top (required)>'
  /home/kpatil/bin/cucumber:23:in`load'
  /home/kpatil/bin/cucumber:23:in `<main>'
App doesn't exist /home/kpatil/Documents/books/testcasedb/cucumber-watir/apps/Movies.app (RuntimeError)
/home/kpatil/.gem/ruby/gems/appium_lib-8.0.2/lib/appium_lib/driver.rb:429:in`absolute_app_path'
/home/kpatil/.gem/ruby/gems/appium_lib-8.0.2/lib/appium_lib/driver.rb:93:in `load_appium_txt'
/home/kpatil/Documents/books/testcasedb/cucumber-watir/features/support/appium.rb:8:in`<top (required)>'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in`load_code_file'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:84:in`block in load_files!'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in `each'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in`load_files!'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:254:in `load_step_definitions'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:62:in`run!'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in `execute!'
/home/kpatil/.gem/ruby/gems/cucumber-2.3.2/bin/cucumber:8:in`<top (required)>'
/home/kpatil/bin/cucumber:23:in `load'
/home/kpatil/bin/cucumber:23:in`<main>'
read() failed: Connection reset by peer

**Comment by bkone** [comment]
Kiran,
the movies.app is part of the react native example repository and will not
work on Linux. You will need to run this on a Mac. Howeveryou can write acceptance tests against a browser application on any OS. Also make sure bundle install has run successfully before you run any tests. It looks like the minitest gem was not installed.

Thanks
bk

**Comment by kirantpatil** [comment]
I have installed minitest.

Ruby version:
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

$ gem list minitest

**\* LOCAL GEMS ***

minitest (5.8.4, 5.8.1, 5.7.0, 5.4.3, 5.3.3)
read() failed: Connection reset by peer

**Comment by kirantpatil** [comment]
Why is it invoking app folder when I am using serach feature as below ?

Feature: Search
  In order to make sure that the search feature is working
  As a user I will search for a search term and expect to see valid results

@desktop
Scenario: search for modus create
  Given I am on the duckduckgo home page
  Then I must see the page title "DuckDuckGo"
  Given I fill in the text field "q" with "Modus Create"
  And I click the "S" button
  Then I must see the page title "Modus Create at DuckDuckGo"

and 
urls.rb file changed as below

def path_to(page_name)
    if ENV["BASE_URL"]
        base_url = ENV["BASE_URL"]
    else
        base_url = BASE_URL[TARGET]
    end
    case page_name
    when /the desktop home page/i
       base_url
    when /the duckduckgo home page/i
       base_url="http://duckduckgo.com"
    else
      raise "Can't find mapping from \"#{page_name}\" to a url.\n" +
        "Please add a mapping in #{**FILE**}"
     end
  end

**Comment by kirantpatil** [comment]
The warning is gone after placing the require 'minitest/autorun' statement above line 4 of env.rb.

The app error is gone after removing your last commit files which are,
 features/reactnative.feature 
 features/step_definitions/appium_steps.rb 
 features/support/appium.rb 
 features/support/appium.txt

**Comment by kirantpatil** [comment]
Please fix the issue which is caused by the last commit 34fb49b1c3c39148ad9b33fc0e5af363517aa293

**Comment by obscurerichard** [comment]
Thanks @kirantpatil, I've reverted the last commit, and pushed it to master.

```
Codex:cucumber-watir rbulling$ git revert HEAD
[master 3ce1e4e] Revert "added support for appium to test ios & android native apps"
 7 files changed, 2 insertions(+), 58 deletions(-)
 delete mode 100644 features/reactnative.feature
 delete mode 100644 features/step_definitions/appium_steps.rb
 delete mode 100644 features/support/appium.rb
 delete mode 100644 features/support/appium.txt
Codex:cucumber-watir rbulling$ git push
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 816 bytes | 0 bytes/s, done.
Total 8 (delta 5), reused 0 (delta 0)
To git@github.com:ModusCreateOrg/cucumber-watir.git
   34fb49b..30b6dd1  master -> master
Codex:cucumber-watir rbulling$ rake
/Users/rbulling/.rvm/rubies/ruby-2.1.1/bin/ruby -S bundle exec cucumber features/*.feature --format html --out=results/all-report-2016-03-18-16-18-13.html --format pretty --no-source --format rerun --out results/all-rerun.txt --tag @regression
Using the default profile...
Feature: Main tests
  In order to make sure that the web page is working
  As a normal user
  I want to check out the home page in a variety of aspect ratios

  @smoke @regression @desktop
  Scenario: Visit the home page
    Given I am on the desktop home page
      URL = http://moduscreate.com/
    Then I must see the page title "Modus Create - HTML5 Application Development & Training"
    Given I click the "Services" span

  @regression @mobile
  Scenario: Visit the home page on a mobile device
    Given I am on the desktop home page
      URL = http://moduscreate.com/
    Then I must see the page title "Modus Create - HTML5 Application Development & Training"
    Given I click the "icon-reorder" icon
    And I wait for the menu to be displayed

2 scenarios (2 passed)
7 steps (7 passed)
0m21.126s
```

If you pull the latest changes to master, you should find that the suite is working as expected again.

**Comment by obscurerichard** [comment]
The Appium changes are now in the `appium` branch, this bug will stay open until we can fix that branch.

@andrewowen perhaps you can take a look at the `appium` branch and triage what needs to be fixed here?

**Comment by obscurerichard** [comment]
I'm going to close this as wontfix for now, as this repo is really focused more on web testing than appium.
