### ISSUE TITLE
[FAQ] Integration with Jmeter

### ISSUE THREAD

**Issue by kirantpatil** [ModusCreateOrg/cucumber-watir#5]
Hi,

How did you provide Jmeter integration with cucumber-watir ?

Have you integrated cucumber-watir with Jmeter ?

Thanks.

**Comment by mmooney-modus** [comment]
@kirantpatil We haven't integrated JMeter and Cucumber-Watir. Combining the two goes a little beyond the scope of their purposes as testing tools.

There's a discussion on [Stack](http://stackoverflow.com/questions/25400995/integrating-jmeter-with-cucumberrubyselenium-framework) that may point you in the right direction for what is achievable.
